- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: app setup nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: app setup mongodb
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup

- name: systemctl
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd